version: '3.4'

services:
  greenapi:
    depends_on:
        - db
    image: ${DOCKER_REGISTRY-}greenapi
    build:
      context: .
      dockerfile: GreenAPI/Dockerfile
    ports: 
        - "8080:5000"
    networks:
        - default_network
  db:
    image: mysql:8.0.27
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: GreenStockDatabase
        MYSQL_USER: fashionstack
        MYSQL_PASSWORD: 12345678
    volumes:
        - dbdata:/var/lib/mysql
    ports:
        - "9000:3306"
    restart: always
    networks:
        - default_network

volumes:
  dbdata:

networks:
  default_network:
    driver: bridge